[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {where = ["src"]}}

[tool.setuptools.package-data]
observability = ["*.py"]

[project]
name = "observability"
version = "0.1.0"
dependencies = []